apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prom-graf-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus.jomokyli.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus 
            port:
              number: 9090
  - host: grafana.jomokyli.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
