apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: spring.jomokyli.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: springapp
            port:
              number: 80
  - host: java.jomokyli.com
    http:
      paths: 
      - pathType: Prefix
        path: /java-web-app
        backend:
          service:
            name: javasvc
            port:
              number: 80
  - host: maven.jomokyli.com
    http:
      paths:
      - pathType: Prefix
        path: /maven-web-app
        backend:
          service:
            name: mavenapp
            port:
              number: 80
