apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp    
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
      - image: mylandmarktech/maven-web-app
        name: mavenapp
        ports:
        - name: javawebapp
          containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
    name: mavenapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
      app: mavenapp
