apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: jomokyli.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: springapp
            port: 
              number: 80
      - path: /java-web-app
        pathType: Prefix
        backend:
          service: 
            name: javasvc
            port: 
              number: 80
      - path: /maven-web-app
        pathType: Prefix
        backend:
          service: 
            name: mavenapp
            port: 
              number: 80



